### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by matrinox** [etsy/es-restlog#2]
From my understanding, this means the server I'm running this plugin on does not have Java 1.8 (it has 1.7). I'm using 0.4; is there a version that uses 1.7?

**Comment by shikhar** [comment]
You will need to build it yourself :-)

I believe just `javaVersion` in `Build.scala` would need to be updated. Also I see a lambda in use in `RestLoggerFilter.pathFilter`, so that'll need to be made into an anon inner class. The Java8 requirement isn't really pulling it's weight, so PR welcome!

See also https://github.com/etsy/es-restlog#packaging

**Comment by shikhar** [comment]
It will be built for Java 11 after https://github.com/etsy/es-restlog/pull/4
